export const GET_ALL_PRODUCT_DETAIL = "GET_ALL_PRODUCT_DETAIL"
export const CREATE_PRODUCT_DETAIL = "CREATE_PRODUCT_DETAIL"
export const UPDATE_PRODUCT_DETAIL_BY_ID = "UPDATE_PRODUCT_DETAIL_BY_ID"
export const DELETE_PRODUCT_DETAIL_BY_ID = "DELETE_PRODUCT_DETAIL_BY_ID"
