export const GET_ALL_GALLERY = "GET_ALL_GALLERY";
export const CREATE_GALLERY = "CREATE_GALLERY";
export const UPDATE_GALLERY_BY_ID = "UPDATE_GALLERY_BY_ID";
export const DELETE_GALLERY_BY_ID = "DELETE_GALLERY_BY_ID";
