export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const DELETE_CATEGORY_BY_ID = "DELETE_CATEGORY_BY_ID";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const UPDATE_CATEGORY_BY_ID = "UPDATE_CATEGORY_BY_ID";