export const GET_ALL_TYPE_GALLERY = "GET_ALL_TYPE_GALLERY";
export const GET_TYPE_GALLERY_BY_ID = "GET_TYPE_GALLERY_BY_ID";
export const UPDATE_TYPE_GALLERY_BY_ID = "UPDATE_TYPE_GALLERY_BY_ID";
export const CREATE_TYPE_GALLERY = "CREATE_TYPE_GALLERY";
export const DELETE_TYPE_GALLERY_BY_ID = "DELETE_TYPE_GALLERY_BY_ID";