export const GET_ALL_ORDER = "GET_ALL_ORDER";
export const GET_ORDER_BY_ID = "GET_ORDER_BY_ID";
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS";
export const GET_ORDER_STATUS = "GET_ORDER_STATUS";
export const COUNT_ORDER = "COUNT_ORDER";
export const GET_ORDER_HOT = "GET_ORDER_HOT";
export const GET_TOTAL_ORDER_BY_MONTH = "GET_TOTAL_ORDER_BY_MONTH";
export const GET_TOTAL_PRICE_BY_MONTH = "GET_TOTAL_PRICE_BY_MONTH";